complexity:
  LongMethod:
    threshold: 60
  LongParameterList:
    functionThreshold: 6
    constructorThreshold: 7
  TooManyFunctions:
    thresholdInFiles: 15
    thresholdInClasses: 15
    thresholdInInterfaces: 15
    thresholdInObjects: 15

style:
  MagicNumber:
    ignoreNumbers: ['-1', '0', '1', '2', '4', '8', '16', '32', '64', '100', '1000', '2048']
  MaxLineLength:
    maxLineLength: 120
  ReturnCount:
    max: 3
  ThrowsCount:
    max: 3
  NewLineAtEndOfFile:
    active: true

naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  VariableNaming:
    variablePattern: '[a-z][a-zA-Z0-9]*'
    privateVariablePattern: '_?[a-z][a-zA-Z0-9]*'

performance:
  SpreadOperator:
    active: true

coroutines:
  active: true
  GlobalCoroutineUsage:
    active: true
  RedundantSuspendModifier:
    active: true
  SuspendFunWithFlowReturnType:
    active: true

exceptions:
  TooGenericExceptionCaught:
    active: true
  SwallowedException:
    active: true

formatting:
  active: true
  android: false
  autoCorrect: true
  MaximumLineLength:
    maxLineLength: 120

comments:
  UndocumentedPublicClass:
    active: true
  UndocumentedPublicFunction:
    active: true

empty-blocks:
  EmptyFunctionBlock:
    active: true
    ignoreOverridden: true

potential-bugs:
  ImplicitDefaultLocale:
    active: true
  DuplicateCaseInWhenExpression:
    active: true